language: objective-c

branches:
  only:
    - master

xcode_project: JASON.xcodeproj
xcode_scheme: JASONTests
osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1

script:
  - xcodebuild test -project JASON.xcodeproj -scheme "JASON iOS Tests" -destination "platform=iOS Simulator,name=iPhone 6s"
