language: swift

branches:
  only:
    - master

xcode_project: JASON.xcodeproj
xcode_scheme: JASONTests
osx_image: xcode11.2

script:
  - xcodebuild test -project JASON.xcodeproj -scheme "JASON iOS" -destination "platform=iOS Simulator,name=iPhone 11"
