language: objective-c

branches:
  only:
    - master

xcode_project: JASON.xcodeproj
xcode_scheme: JASONTests
osx_image: xcode6.4
xcode_sdk: iphonesimulator8.4

script:
  - xcodebuild test -project JASON.xcodeproj -scheme "JASON iOS Tests"
